In [17]:
# 我们研究一天之内的数据, 所以在程序的开始加载当日的所有数据.
Date = '2023-01-04'

In [18]:
# 在本次研究中, 我们关注的Contious Count Station 为:
# [601, 626, 632, 635, 643, 645, 647, 648, 656, 658, 662, 671, 672, 675, 676] 

Utah_Vehicles_Person = 0.850 # vehicles per person in Utah
Region_1_population = 19902# Highland population
Region_2_population = 0.5 * 84373 # half of population of Lehi 2022
Region_3_population = 0.5 * 84373 # the other half of population of Lehi 2022
Region_4_population = 37268 + 37630 # the population of American Fork and Pleasant Grove 2022
Region_5_population = 17865 # Heber City which is far from Highland
Region_6_population = 19080+59179+50731 # Bluffdale + Herriman + Draper population
Region_7_population = 54149  # Eagle Mountain population
region_8_population = 11704 + 95910 + 14535 # Lindon + Orem + Vineyard population

## suppose the total number of cars in the city
region_1_initial_traffic_amount = int(Region_1_population * Utah_Vehicles_Person)
region_2_initial_traffic_amount = int(Region_2_population * Utah_Vehicles_Person)
region_3_initial_traffic_amount = int(Region_3_population * Utah_Vehicles_Person)
region_4_initial_traffic_amount = int(Region_4_population * Utah_Vehicles_Person)
region_5_initial_traffic_amount = int(Region_5_population * Utah_Vehicles_Person)
region_6_initial_traffic_amount = int(Region_6_population * Utah_Vehicles_Person)
region_7_initial_traffic_amount = int(Region_7_population * Utah_Vehicles_Person)
region_8_initial_traffic_amount = int(region_8_population * Utah_Vehicles_Person)

In [19]:
import model
import numpy as np

_initial_traffic_amouts_list = [region_1_initial_traffic_amount, region_2_initial_traffic_amount, 
                                region_3_initial_traffic_amount, region_4_initial_traffic_amount, 
                                region_5_initial_traffic_amount, region_6_initial_traffic_amount, 
                                region_7_initial_traffic_amount, region_8_initial_traffic_amount]

# initialization of CCSs
CCS_601, CCS_626, CCS_632, CCS_635, CCS_643,\
CCS_645, CCS_647, CCS_648, CCS_656, CCS_658,\
CCS_662, CCS_671, CCS_672, CCS_675, CCS_676,\
Region_1, Region_2, Region_3, Region_4,\
Region_5, Region_6, Region_7, Region_8 = \
model.initialize_CSSs_and_Regions(date=Date, 
                                  initials_traffic_amount_list=_initial_traffic_amouts_list)

model.initialize_region_transition_matrix_v2()

CCS idx:  645
CCS idx:  656
The initial traffic amount of Region  1  is  16916
The initial traffic amount of Region  2  is  35858
The initial traffic amount of Region  3  is  35858
The initial traffic amount of Region  4  is  63663
The initial traffic amount of Region  5  is  15185
The initial traffic amount of Region  6  is  109641
The initial traffic amount of Region  7  is  46026
The initial traffic amount of Region  8  is  103826


In [20]:
print("The traffic amount of each region during the day: ")
print(model.current_time_traffic_amount)

The traffic amount of each region during the day: 
[[ 16916.  35858.  35858.  63663.  15185. 109641.  46026. 103826.]
 [ 16943.  35946.  35707.  63602.  15179. 109742.  46116. 103738.]
 [ 16967.  35905.  35620.  63649.  15183. 109826.  46160. 103663.]
 [ 16969.  35914.  35586.  63688.  15181. 109895.  46145. 103595.]
 [ 16968.  35946.  35642.  63821.  15178. 109753.  46082. 103583.]
 [ 16930.  35971.  35902.  64095.  15178. 109400.  45834. 103663.]
 [ 16932.  35833.  36694.  65058.  15179. 108329.  45168. 103780.]
 [ 16559.  36233.  37943.  66497.  15183. 106229.  44296. 104033.]
 [ 16150.  36407.  39751.  68752.  15191. 104467.  42768. 103487.]
 [ 15477.  35416.  40055.  71770.  15211. 105269.  41848. 101927.]
 [ 15015.  35400.  40130.  73566.  15220. 105785.  41306. 100551.]
 [ 14797.  36092.  40489.  74286.  15229. 105576.  40967.  99537.]
 [ 14551.  36569.  40764.  74423.  15236. 105759.  40824.  98847.]
 [ 14319.  37533.  40645.  74251.  15243. 105610.  40808.  98564.]
 [ 14232.  

In [21]:
np.set_printoptions(precision=5, suppress=True)
np.set_printoptions(threshold=np.inf)
print("The transition amount among different regions: ")
print()
for _ in range(model.hourly_traffic_among_regions.shape[0]):
    print(f'The transition amount during {_}:00 to {_+1}:00')
    print(model.hourly_traffic_among_regions[_])
    print()
    

The transition amount among different regions: 

The transition amount during 0:00 to 1:00
[[ 16837.     76.      0.      0.      3.      0.      0.      0.]
 [    97.  34210.    111.    644.      0.    796.      0.      0.]
 [     0.    260.  35351.     98.      0.      0.    149.      0.]
 [     0.    705.    186.  61967.      0.      0.      0.    805.]
 [     9.      0.      0.      0.  15176.      0.      0.      0.]
 [     0.    695.      0.      0.      0. 108946.      0.      0.]
 [     0.      0.     59.      0.      0.      0.  45967.      0.]
 [     0.      0.      0.    893.      0.      0.      0. 102933.]]

The transition amount during 1:00 to 2:00
[[ 16910.     28.      0.      0.      5.      0.      0.      0.]
 [    56.  34918.     63.    411.      0.    498.      0.      0.]
 [     0.    125.  35459.     54.      0.      0.     69.      0.]
 [     0.    420.     73.  62624.      0.      0.      0.    485.]
 [     1.      0.      0.      0.  15178.      0.      0.    

In [22]:
np.set_printoptions(precision=10, suppress=True)

print()
# print(get_hour_k_step_transition_matrix(1, 2))
print()
print(model.get_hour_k_step_transition_matrix(0, 9))
print()
print(np.dot(model.get_hour_k_step_transition_matrix(0, 7), model.get_hour_k_step_transition_matrix(7, 2)))
print()
print( np.allclose(model.get_hour_k_step_transition_matrix(0, 9),  
                   np.dot(model.get_hour_k_step_transition_matrix(0, 7), 
                          model.get_hour_k_step_transition_matrix(7, 2))) )



[[0.7522263469 0.1610128263 0.0137692748 0.0318555146 0.0032778707
  0.0355869684 0.0001892964 0.0020819018]
 [0.0417305737 0.2293585186 0.1214470627 0.2533109777 0.0000883888
  0.2956559087 0.0043790406 0.0540295293]
 [0.0031252635 0.0681929011 0.6760196654 0.1488091176 0.0000032762
  0.0196125887 0.0625333115 0.0217038761]
 [0.0061093668 0.1185596261 0.0498622289 0.5259369699 0.0000067511
  0.0384005551 0.0014574945 0.2596670077]
 [0.0019069032 0.0002292292 0.0000158809 0.0000371373 0.9977671048
  0.0000414445 0.0000001936 0.0000021065]
 [0.00623569   0.1133986646 0.015548362  0.034700998  0.0000065376
  0.8268734472 0.000269031  0.0029672695]
 [0.0001080792 0.0054990464 0.1274007442 0.0113767674 0.000000049
  0.0006535632 0.8542217858 0.0007399648]
 [0.0003596385 0.0171934179 0.0046559837 0.1830017652 0.0000002147
  0.0021909413 0.0000650568 0.7925329819]]

[[0.7522263469 0.1610128263 0.0137692748 0.0318555146 0.0032778707
  0.0355869684 0.0001892964 0.0020819018]
 [0.0417305737 0

In [23]:
test_atol = 2e-2
false_case_count = 0
count = 0
for begin_hour in range(0, 24):
    for k in range(1, 24):
        for l in range(1, 24):
            if begin_hour + k + l >= 24:
                continue
            count += 1
            
			# print(get_hour_k_step_transition_matrix(begin_hour, k))
            tmp_bool = np.allclose(
                model.get_hour_k_step_transition_matrix(begin_hour, k+l),
                np.dot(model.get_hour_k_step_transition_matrix(begin_hour, k), 
                       model.get_hour_k_step_transition_matrix(begin_hour + k, l)), 
			)
            if not tmp_bool:
                print((begin_hour, k, l), ' this is the pair of (begin_hour, k, l)')
                false_case_count += 1

print(count, " this is the count")
print(false_case_count, " this is the false case count")

2024  this is the count
0  this is the false case count


In [24]:
# 实验 0: 离散时间马尔科夫链 k 步转移概率矩阵的计算
exp0_begin_hour = 0 
exp0_k = 5

print("Experiment 0")
print('The construction of Markov Chain and the calculation of k-step transition probability matrix')
print('--------------------------------------------------')
# # print(Region_1.getTransitionMatrix2Regions(begin_hour=exp0_hour1, end_hour=exp0_hour3))

print(f"The {exp0_k}-step transition matrix from hour {exp0_begin_hour}")
print(model.get_hour_k_step_transition_matrix(begin_hour=exp0_begin_hour, k=exp0_k))

Experiment 0
The construction of Markov Chain and the calculation of k-step transition probability matrix
--------------------------------------------------
The 5-step transition matrix from hour 0
[[0.9844283927 0.0141073345 0.0001000432 0.0003684498 0.0006464278
  0.0003457101 0.0000001108 0.0000035311]
 [0.0068681506 0.8444942206 0.014918352  0.0639403918 0.0000015379
  0.0685430255 0.0000392506 0.0011950709]
 [0.000051876  0.0170542394 0.9569735787 0.0144051392 0.000000002
  0.0005869097 0.010720576  0.000207679 ]
 [0.000087474  0.0330524964 0.0070290145 0.9138798042 0.000000003
  0.0009898659 0.0000304349 0.044930907 ]
 [0.0011743182 0.0000102107 0.0000000329 0.0000001071 0.9988152403
  0.0000000903 0.           0.0000000004]
 [0.000053063  0.0245519889 0.000180023  0.0006495359 0.0000000017
  0.9745595506 0.000000179  0.0000056578]
 [0.0000000352 0.0000319309 0.012518772  0.0000458253 0.
  0.0000003978 0.9874028041 0.0000002347]
 [0.0000004876 0.0003968684 0.00006541   0.02914295

In [25]:
# 实验1: 查普曼-柯尔莫哥洛夫方程验证
exp1_m = 5
exp1_k = 10
exp1_l = 4

exp1_P_begin_m_step_k_plus_l = model.get_hour_k_step_transition_matrix(
    								begin_hour=exp1_m, 
                                    k=exp1_k+exp1_l)

exp1_P_begin_m_step_k = model.get_hour_k_step_transition_matrix(
									begin_hour=exp1_m, 
									k=exp1_k)	

exp1_P_begin_m_plus_k_step_l = model.get_hour_k_step_transition_matrix(
									begin_hour=exp1_m+exp1_k, 
									k=exp1_l)	

print("Experiment 1")
print('The Chapman-Kolmogorov equation verification')
print('--------------------------------------------------')
print("The left side of the Chapman-Kolmogorov equation")
print(exp1_P_begin_m_step_k_plus_l)
print()
print("The right side of the Chapman-Kolmogorov equation")
print(np.dot(exp1_P_begin_m_step_k, exp1_P_begin_m_plus_k_step_l))
print()
print("The equality of the left side and the right side of the Chapman-Kolmogorov equation")
print(np.allclose(exp1_P_begin_m_step_k_plus_l, 
				  np.dot(exp1_P_begin_m_step_k, exp1_P_begin_m_plus_k_step_l)))


Experiment 1
The Chapman-Kolmogorov equation verification
--------------------------------------------------
The left side of the Chapman-Kolmogorov equation
[[0.2506058269 0.1693671176 0.0646380422 0.1358869916 0.0158096418
  0.2600794715 0.016994452  0.0866184563]
 [0.0495052355 0.1262049758 0.0994541392 0.1593780286 0.0013739797
  0.3448476217 0.0438547831 0.1753812364]
 [0.0276242593 0.1102931417 0.2518682041 0.1556875836 0.0003426976
  0.1305146811 0.1850447622 0.1386246704]
 [0.0322355785 0.1092912909 0.0846435845 0.2240014307 0.0005065758
  0.163675691  0.0274415028 0.3582043458]
 [0.0174510871 0.0049318644 0.0005777729 0.0017172704 0.972232541
  0.0025630259 0.0000694184 0.0004570199]
 [0.0360223586 0.1325303742 0.0443310845 0.0942868838 0.0005163503
  0.6213757889 0.0119326711 0.0590044885]
 [0.0063437213 0.0370743964 0.1562929921 0.0430774328 0.0000470468
  0.0269624525 0.7060095619 0.0241923962]
 [0.0160048253 0.0814676324 0.0502231965 0.2398649274 0.0001346311
  0.069027515

In [26]:
# 实验2: 时齐离散马尔科夫链的构造与极限分布与平稳分布的计算

# # Suppose the traffic flow is a time-homogeneous Markov chain
# # The transition matrix is the same for all hours
exp2_begin_hour = 0
exp2_k = 1
exp2_initial_distribution_time = 10

exp2_initial_distribution = model.current_time_traffic_amount[exp2_initial_distribution_time]
exp2_initial_distribution = exp2_initial_distribution / np.sum(exp2_initial_distribution)
exp2_transition_matrix_P = model.get_hour_k_step_transition_matrix(
								begin_hour=exp2_begin_hour,
								k=exp2_k)

# 根据transition matrix和初始分别计算极限分布
def compute_limit_distribution(transition_matrix, initial_distribution, alltol = 1e-6):
	next_distribution = np.dot(initial_distribution, transition_matrix)
	while not np.allclose(initial_distribution, next_distribution, atol=alltol):
		initial_distribution = next_distribution
		next_distribution = np.dot(initial_distribution, transition_matrix)
	return next_distribution

print("Experiment 2")
print('The construction of time-homogeneous Markov Chain and the calculation of limit distribution')
print('--------------------------------------------------')
print('The transition matrix of the traffic flow:')
print(exp2_transition_matrix_P)
print()
print('The initial distribution of the traffic flow:')
print(exp2_initial_distribution)
print()
exp2_limit_distribution = compute_limit_distribution(exp2_transition_matrix_P, exp2_initial_distribution)
print('The limit distribution of the traffic flow:')
print(exp2_limit_distribution)



# 根据transition matrix计算平稳分布
def compute_stationary_distribution(transition_matrix):
	eigenvalues, eigenvectors = np.linalg.eig(transition_matrix.T)
	stationary_index = np.where(np.isclose(eigenvalues, 1))[0][0]
	stationary_distribution = np.real(eigenvectors[:, stationary_index])
	stationary_distribution /= np.sum(stationary_distribution)
	return stationary_distribution


print("Experiment 2")
print('The construction of time-homogeneous Markov Chain and the calculation of stationary distribution')
print('--------------------------------------------------')
exp2_stationary_distribution = compute_stationary_distribution(exp2_transition_matrix_P)
print('The stationary distribution of the traffic flow:')
print(exp2_stationary_distribution)


Experiment 2
The construction of time-homogeneous Markov Chain and the calculation of limit distribution
--------------------------------------------------
The transition matrix of the traffic flow:
[[0.9953298652 0.0044927879 0.           0.           0.0001773469
  0.           0.           0.          ]
 [0.0027051146 0.9540409393 0.0030955435 0.01795973   0.
  0.0221986725 0.           0.          ]
 [0.           0.0072508227 0.9858608958 0.0027330024 0.
  0.           0.0041552792 0.          ]
 [0.           0.0110739362 0.0029216342 0.9733597223 0.
  0.           0.           0.0126447073]
 [0.0005926902 0.           0.           0.           0.9994073098
  0.           0.           0.          ]
 [0.           0.0063388696 0.           0.           0.
  0.9936611304 0.           0.          ]
 [0.           0.           0.0012818842 0.           0.
  0.           0.9987181158 0.          ]
 [0.           0.           0.           0.0086009285 0.
  0.           0.           0.9

In [27]:
# 实验3: 非时齐离散马尔科夫链的构造, 尝试用一些简单的方法构造非时齐马尔科夫链

# 6 - 9这个时间段.
# 我们使用线性建模转移概率矩阵的方式来构造非时齐的马尔科夫链
exp3_begin_hour = 6
exp3_end_hour = 9


# 我们结合6-7 的转移矩阵和 7-8 的转移矩阵来构造 8-9 的转移矩阵
exp3_transition_matrix_6_7 = model.get_hour_k_step_transition_matrix(begin_hour=exp3_begin_hour, k=1)
exp3_transition_matrix_7_8 = model.get_hour_k_step_transition_matrix(begin_hour=exp3_begin_hour+1, k=1)
exp3_model_transition_matrix_8_9 = 2 * exp3_transition_matrix_7_8 - exp3_transition_matrix_6_7
exp3_real_transition_matrix_8_9 = model.get_hour_k_step_transition_matrix(begin_hour=exp3_begin_hour+2, k=1)



print("Experiment 3")
print('The construction of non-time-homogeneous Markov Chain')
print('--------------------------------------------------')
print('The transition matrix of the traffic flow from 6:00 to 7:00:')
print(exp3_transition_matrix_6_7)
print()
print('The transition matrix of the traffic flow from 7:00 to 8:00:')
print(exp3_transition_matrix_7_8)
print()
print('The model transition matrix of the traffic flow from 8:00 to 9:00:')
print(exp3_model_transition_matrix_8_9)
print()
print('The real transition matrix of the traffic flow from 8:00 to 9:00:')
print(exp3_real_transition_matrix_8_9)
print()

# # TODO(BobHuangC) 预测具体的交通流量
print('The real transition number is ')
print(model.hourly_traffic_among_regions[8][0])

print('The Non Time Alignment model transition number is ')
print(model.current_time_traffic_amount[8] * exp3_model_transition_matrix_8_9[0])

print('The Time Alignment model transition number is ')
print(model.current_time_traffic_amount[8] * (exp3_transition_matrix_6_7+exp3_transition_matrix_7_8)[0]/2)

Experiment 3
The construction of non-time-homogeneous Markov Chain
--------------------------------------------------
The transition matrix of the traffic flow from 6:00 to 7:00:
[[0.9570635483 0.0426411528 0.           0.           0.0002952988
  0.           0.           0.          ]
 [0.0098512544 0.7255044233 0.0511818715 0.1167080624 0.
  0.0967543884 0.           0.          ]
 [0.           0.0209025999 0.9233117131 0.037254047  0.
  0.           0.0185316401 0.          ]
 [0.           0.0488794614 0.0104060992 0.8671493129 0.
  0.           0.           0.0735651265]
 [0.0000658805 0.           0.           0.           0.9999341195
  0.           0.           0.          ]
 [0.           0.0513897479 0.           0.           0.
  0.9486102521 0.           0.          ]
 [0.           0.           0.0343606093 0.           0.
  0.           0.9656393907 0.          ]
 [0.           0.           0.           0.0436789362 0.
  0.           0.           0.9563210638]]

The tra

In [28]:
# 实验4: 时齐连续马尔科夫链的构造与Q矩阵的计算与极限分布与平稳分布的计算, 

# 转移速率矩阵Q的计算
# TODO(BobHuangC): check the correctness of this function
# input a list of x and a list of matrix, for each element of matrix, build the linear model of x to the element
# 返回一个function, 这个function的输入是x的一个元素, 输出是一个矩阵
def linearModelMatrix(X, matrix):
    def linearModel(x, y):
        p = np.polyfit(x, y, 1)
        f = np.poly1d(p)
        return f
    _matrix_shape = matrix[0].shape
    _matrix_len = len(matrix)
    _f_list = []
    for i in range(_matrix_shape[0]):
        _f_list.append([])
        for j in range(_matrix_shape[1]):
            _f_list[i].append(linearModel(X, [matrix[k][i][j] for k in range(_matrix_len)]))

    def _f(x):
        _result = np.zeros(_matrix_shape)
        for i in range(_matrix_shape[0]):
            for j in range(_matrix_shape[1]):
                _result[i][j] = _f_list[i][j](x)
        return _result
    return _f


# 返回一个Q矩阵
# begin_hour: 起始小时
# n_hour_steps: 一共用多少个小时的transition matrix来拟合Q矩阵
# epsilon: 最终用趋近于0的epsilon来计算Q矩阵
def get_hour_Q_matrix(begin_hour, n_hour_steps, epsilon):
    trans_matrixs_list = [model.get_hour_k_step_transition_matrix(begin_hour, k) for k in range(1, n_hour_steps+1)]
    phi_t_list = [i - np.eye(8) for i in trans_matrixs_list]
    phi_t_list = [phi_t_list[i] / (i+1) for i in range(n_hour_steps)]
    Phi_t = linearModelMatrix(list(range(1, 1+n_hour_steps)), 
                              phi_t_list)
    return Phi_t(epsilon)
    



exp4_begin_hour1 = 12
exp4_fitting_hour_steps = 4
exp4_epsilon = 0.1
exp4_Q = get_hour_Q_matrix(begin_hour=exp4_begin_hour1, n_hour_steps=exp4_fitting_hour_steps, epsilon=exp4_epsilon)

exp4_transition_matrix_P1 = model.get_hour_k_step_transition_matrix(begin_hour=exp4_begin_hour1, k=1)
exp4_transition_matrix_P2 = model.get_hour_k_step_transition_matrix(begin_hour=exp4_begin_hour1, k=2)
exp4_transition_matrix_P3 = model.get_hour_k_step_transition_matrix(begin_hour=exp4_begin_hour1, k=3)
exp4_transition_matrix_P4 = model.get_hour_k_step_transition_matrix(begin_hour=exp4_begin_hour1, k=4)


print("Experiment 4")
print('The construction of time-homogeneous continuous Markov Chain')
print('--------------------------------------------------')
print('The Q matrix of the traffic flow:')
print(exp4_Q)
print()
print('The transition matrix of the traffic flow from 12:00 to 13:00:')
print(exp4_transition_matrix_P1)
print()
print('The transition matrix of the traffic flow from 12:00 to 14:00:')
print(exp4_transition_matrix_P2)
print()
print('The transition matrix of the traffic flow from 12:00 to 15:00:')
print(exp4_transition_matrix_P3)
print()
print('The transition matrix of the traffic flow from 12:00 to 16:00:')
print(exp4_transition_matrix_P4)
print()

Experiment 4
The construction of time-homogeneous continuous Markov Chain
--------------------------------------------------
The Q matrix of the traffic flow:
[[-0.144417628   0.1525599482 -0.0013237875 -0.0031431007  0.0024705162
  -0.0051508894 -0.0000878363 -0.0009072224]
 [ 0.0531883339 -0.4390173745  0.0492818905  0.1823882414 -0.0000486955
   0.1584489658 -0.0005061463 -0.0037352153]
 [-0.0005188432  0.0424664971 -0.1043975108  0.0395343983 -0.0000031929
  -0.002108823   0.0265823295 -0.001554855 ]
 [-0.0008582823  0.098701552   0.0186082181 -0.210926484  -0.0000067846
  -0.0035760849 -0.0003403118  0.0983981775]
 [ 0.0019016641 -0.0001069153 -0.0000056071 -0.000019649  -0.0017470169
  -0.0000218963 -0.0000000499 -0.0000005295]
 [-0.0006457253  0.0565556642 -0.0006759171 -0.0017924488 -0.000004178
  -0.0530322571 -0.0000357028 -0.0003694351]
 [-0.0000237106 -0.0004258436  0.0285481394 -0.0004166275 -0.0000000265
  -0.0000888994 -0.0275428522 -0.0000501796]
 [-0.0001291818 -0.0015

In [29]:
# 实验5: 时齐连续马尔科夫链根据Q矩阵计算平稳分布

# 根据Q计算平稳分布
# TODO(BobHuangC): make the function to compute the
from copy import deepcopy
def compute_stationary_distribution_by_Q(Q):
	_Q = deepcopy(Q)
	_Q = _Q.T
	_Q[-1] = np.ones(8)
	b = np.zeros(8)
	b[-1] = 1
	return np.linalg.solve(_Q, b)


exp5_begin_hour = 8
exp5_fitting_hour_steps = 4
exp5_epsilon = 0.5
exp5_Q = get_hour_Q_matrix(begin_hour=exp5_begin_hour, n_hour_steps=exp5_fitting_hour_steps, epsilon=exp5_epsilon)

exp5_stationary_distribution = compute_stationary_distribution_by_Q(exp5_Q)

print("Experiment 5")
print('The calculation of stationary distribution by Q matrix')
print('--------------------------------------------------')
print('The Q matrix of the traffic flow:')
print(exp5_Q)
print()
print('The stationary distribution of the traffic flow:')
print(exp5_stationary_distribution)

Experiment 5
The calculation of stationary distribution by Q matrix
--------------------------------------------------
The Q matrix of the traffic flow:
[[-0.1129871796  0.1128079849 -0.0001750714 -0.0004957066  0.001904023
  -0.0007102407 -0.0000308647 -0.0003129449]
 [ 0.0319879105 -0.4721416894  0.0656971621  0.1779638607 -0.0000083202
   0.196921598  -0.0001276774 -0.0002928441]
 [-0.0001884196  0.0360562339 -0.1262041902  0.0697545931 -0.0000007084
  -0.0004609613  0.0214542247 -0.0004107722]
 [-0.0002629089  0.0954781154  0.0161999205 -0.2268261359 -0.0000016847
  -0.0002894043 -0.000074788   0.1157768858]
 [ 0.0006878843 -0.0000244755 -0.000001043  -0.0000032954 -0.0006555843
  -0.0000034205 -0.0000000056 -0.00000006  ]
 [-0.0002618247  0.0604338016 -0.0001439154 -0.0004201793 -0.0000011258
  -0.0594209578 -0.0000166558 -0.0001691429]
 [-0.0000129222 -0.0000497927  0.0425708733 -0.0000775598 -0.00000001
  -0.0000493722 -0.0423403743 -0.000040842 ]
 [-0.0000665106 -0.0002836668 -

In [30]:
# 实验6: 非时齐连续马尔科夫链的构造, 尝试用一些简单的方法构造非时齐马尔科夫链

# # 对Q采取线性插值的方式来构造非时齐的Q矩阵
exp6_begin_hour1 = 6
exp6_begin_hour2 = 7

exp6_fitting_hour_steps = 3
exp6_epsilon = 0.1

exp6_Q1 = get_hour_Q_matrix(begin_hour=exp6_begin_hour1, n_hour_steps=exp6_fitting_hour_steps, epsilon=exp6_epsilon)
exp6_Q2 = get_hour_Q_matrix(begin_hour=exp6_begin_hour2, n_hour_steps=exp6_fitting_hour_steps, epsilon=exp6_epsilon)
exp6_model_Q3 = 2 * exp6_Q2 - exp6_Q1
exp6_real_Q3 = get_hour_Q_matrix(begin_hour=exp6_begin_hour2+exp6_fitting_hour_steps, n_hour_steps=exp6_fitting_hour_steps, epsilon=exp6_epsilon)

print("Experiment 6")
print('The construction of non-time-homogeneous continuous Markov Chain')
print('--------------------------------------------------')
print('The Q matrix of the traffic flow from 6:00 to 7:00:')
print(exp6_Q1)
print()
print('The Q matrix of the traffic flow from 7:00 to 8:00:')
print(exp6_Q2)
print()
print('The model Q matrix of the traffic flow from 8:00 to 9:00:')
print(exp6_model_Q3)
print()
print('The real Q matrix of the traffic flow from 8:00 to 9:00:')
print(exp6_real_Q3)
print()



Experiment 6
The construction of non-time-homogeneous continuous Markov Chain
--------------------------------------------------
The Q matrix of the traffic flow from 6:00 to 7:00:
[[-0.0306842917  0.040729293  -0.0015041314 -0.0038877349 -0.0000030814
  -0.004477301  -0.0000148213 -0.0001579313]
 [ 0.009406982  -0.2979075326  0.0579517198  0.1343115388 -0.0000124606
   0.1018830488 -0.0004886779 -0.0051446182]
 [-0.0003131025  0.0219250176 -0.0720657087  0.035420608  -0.0000002492
  -0.0019337285  0.0191204975 -0.0021533343]
 [-0.0006513554  0.0544850769  0.0094198418 -0.1340650689 -0.0000005828
  -0.0040306471 -0.0001265335  0.074969269 ]
 [-0.0000693963 -0.0000070138 -0.0000000772 -0.0000002089  0.0000769271
  -0.0000002308  0.            0.          ]
 [-0.0006448243  0.0604022075 -0.0013441361 -0.003417087  -0.0000006128
  -0.0547873515 -0.0000178621 -0.0001903337]
 [-0.0000077478 -0.0005295195  0.0351801993 -0.0011168096  0.
  -0.0000470973 -0.0334300986 -0.0000489265]
 [-0.00002

In [31]:
# 实验6 extension
# 使用Q矩阵预测具体的交通流量

from scipy.linalg import expm

# 预测多少个小时后的交通流量
exp6_predict_hour = 1
exp6_model_hour_P = expm(exp6_model_Q3 * exp6_predict_hour)
exp6_real_hour_P = expm(exp6_real_Q3 * exp6_predict_hour)

print("Experiment 6 extension")
print('The prediction of traffic flow by Q matrix')
print('--------------------------------------------------')
print('The real transition matrix of the traffic flow from 8:00 to 9:00:')
print(exp6_real_hour_P)
print()
print('The model transition matrix of the traffic flow from 8:00 to 9:00:')
print(exp6_model_hour_P)
print()


Experiment 6 extension
The prediction of traffic flow by Q matrix
--------------------------------------------------
The real transition matrix of the traffic flow from 8:00 to 9:00:
[[ 0.9143368226  0.0801987893  0.0005749213  0.0012638712  0.0018232717
   0.0022810758 -0.0000405137 -0.0004382381]
 [ 0.0295377406  0.6845822917  0.0394965838  0.1107037467  0.0000040708
   0.1340367951  0.0000234496  0.0016153218]
 [ 0.0000028454  0.0235459523  0.9238886509  0.0346018327 -0.0000010941
   0.0005769703  0.0172120855  0.0001727569]
 [ 0.0002230173  0.0616007627  0.0132223554  0.849265124  -0.0000025921
   0.0022478103 -0.000048884   0.0734924063]
 [ 0.0012042977 -0.0000119203 -0.0000031347 -0.0000099353  0.9988313369
  -0.000010166  -0.0000000309 -0.0000004475]
 [ 0.0001947996  0.0468233794  0.0004703968  0.0011857725 -0.0000019225
   0.9515797848 -0.0000218493 -0.0002303613]
 [-0.0000152672  0.0000171205  0.0263070697  0.0001011169 -0.0000000187
  -0.0000507388  0.973676931  -0.0000362134