In [1]:
# 我们研究一天之内的数据, 所以在程序的开始加载当日的所有数据.
Date = '2023-01-04'

In [2]:
# 在本次研究中, 我们关注的Contious Count Station 为:
# [601, 626, 632, 635, 643, 645, 647, 648, 656, 658, 662, 671, 672, 675, 676] 

Utah_Vehicles_Person = 0.850 # vehicles per person in Utah
Region_1_population = 19902# Highland population
Region_2_population = 0.5 * 84373 # half of population of Lehi 2022
Region_3_population = 0.5 * 84373 # the other half of population of Lehi 2022
Region_4_population = 37268 + 37630 # the population of American Fork and Pleasant Grove 2022
Region_5_population = 17865 # Heber City which is far from Highland
Region_6_population = 19080+59179+50731 # Bluffdale + Herriman + Draper population
Region_7_population = 54149  # Eagle Mountain population
region_8_population = 11704 + 95910 + 14535 # Lindon + Orem + Vineyard population

## suppose the total number of cars in the city
region_1_initial_traffic_amount = int(Region_1_population * Utah_Vehicles_Person)
region_2_initial_traffic_amount = int(Region_2_population * Utah_Vehicles_Person)
region_3_initial_traffic_amount = int(Region_3_population * Utah_Vehicles_Person)
region_4_initial_traffic_amount = int(Region_4_population * Utah_Vehicles_Person)
region_5_initial_traffic_amount = int(Region_5_population * Utah_Vehicles_Person)
region_6_initial_traffic_amount = int(Region_6_population * Utah_Vehicles_Person)
region_7_initial_traffic_amount = int(Region_7_population * Utah_Vehicles_Person)
region_8_initial_traffic_amount = int(region_8_population * Utah_Vehicles_Person)

In [3]:
import model
import numpy as np

_initial_traffic_amouts_list = [region_1_initial_traffic_amount, region_2_initial_traffic_amount, 
                                region_3_initial_traffic_amount, region_4_initial_traffic_amount, 
                                region_5_initial_traffic_amount, region_6_initial_traffic_amount, 
                                region_7_initial_traffic_amount, region_8_initial_traffic_amount]

# initialization of CCSs
CCS_601, CCS_626, CCS_632, CCS_635, CCS_643,\
CCS_645, CCS_647, CCS_648, CCS_656, CCS_658,\
CCS_662, CCS_671, CCS_672, CCS_675, CCS_676,\
Region_1, Region_2, Region_3, Region_4,\
Region_5, Region_6, Region_7, Region_8 = \
model.initialize_CSSs_and_Regions(date=Date, 
                                  initials_traffic_amount_list=_initial_traffic_amouts_list)
model.initialize_region_transition_amount()
model.initialize_region_transition_matrix()
model.initialize_region_transition_matrix_v2()

CCS idx:  645
CCS idx:  656
The initial traffic amount of Region  1  is  16916
The initial traffic amount of Region  2  is  35858
The initial traffic amount of Region  3  is  35858
The initial traffic amount of Region  4  is  63663
The initial traffic amount of Region  5  is  15185
The initial traffic amount of Region  6  is  109641
The initial traffic amount of Region  7  is  46026
The initial traffic amount of Region  8  is  103826


In [4]:
print(model.current_time_traffic_amount)

[[ 16916.  16943.  16967.  16969.  16968.  16930.  16932.  16559.  16150.
   15477.  15015.  14797.  14551.  14319.  14232.  14317.  14470.  14572.
   14901.  15237.  15506.  15732.  15934.  16035.  16108.]
 [ 35858.  35946.  35905.  35914.  35946.  35971.  35833.  36233.  36407.
   35416.  35400.  36092.  36569.  37533.  38345.  38893.  39389.  41414.
   42893.  43090.  43821.  44064.  44384.  44588.  44623.]
 [ 35858.  35707.  35620.  35586.  35642.  35902.  36694.  37943.  39751.
   40055.  40130.  40489.  40764.  40645.  40489.  40266.  39771.  38993.
   37977.  36368.  35333.  34637.  34205.  33862.  33656.]
 [ 63663.  63602.  63649.  63688.  63821.  64095.  65058.  66497.  68752.
   71770.  73566.  74286.  74423.  74251.  74243.  73557.  72068.  69768.
   67421.  65161.  64029.  62871.  62110.  61584.  61377.]
 [ 15185.  15179.  15183.  15181.  15178.  15178.  15179.  15183.  15191.
   15211.  15220.  15229.  15236.  15243.  15251.  15267.  15271.  15250.
   15210.  15191.  15205

In [5]:
np.set_printoptions(precision=3, suppress=True)
np.set_printoptions(threshold=np.inf)
print(model.hourly_traffic_among_regions)

[[[ 16837.     76.      0.      0.      3.      0.      0.      0.]
  [    97.  34210.    111.    644.      0.    796.      0.      0.]
  [     0.    260.  35351.     98.      0.      0.    149.      0.]
  [     0.    705.    186.  61967.      0.      0.      0.    805.]
  [     9.      0.      0.      0.  15176.      0.      0.      0.]
  [     0.    695.      0.      0.      0. 108946.      0.      0.]
  [     0.      0.     59.      0.      0.      0.  45967.      0.]
  [     0.      0.      0.    893.      0.      0.      0. 102933.]]

 [[ 16910.     28.      0.      0.      5.      0.      0.      0.]
  [    56.  34918.     63.    411.      0.    498.      0.      0.]
  [     0.    125.  35459.     54.      0.      0.     69.      0.]
  [     0.    420.     73.  62624.      0.      0.      0.    485.]
  [     1.      0.      0.      0.  15178.      0.      0.      0.]
  [     0.    414.      0.      0.      0. 109328.      0.      0.]
  [     0.      0.     25.      0.      0.    

In [6]:
print(model.region_transition_matrix == model.region_transition_matrix_v2)

[[[[ True  True False False False  True  True  True  True  True  True
    False  True  True  True  True False False False False False False
    False False False]
   [ True  True False False False False False False False False False
    False False False False False False False False False False False
    False False  True]
   [ True  True  True False  True  True  True False  True False  True
     True  True  True  True  True False False False False False False
    False  True  True]
   [ True  True  True False False False  True False False False False
    False False False False False False False False False False False
     True  True  True]
   [ True  True  True  True  True  True  True  True  True  True  True
    False  True  True False False False False False False False  True
     True  True  True]
   [ True  True  True  True  True  True  True  True  True  True  True
     True  True False False  True  True False False False  True  True
     True  True  True]
   [ True  True False 

In [7]:
def get_hour_k_step_transition_matrix(begin_hour, k):
	return (np.array([model.region_transition_matrix[i][j][begin_hour][k] for i in range(8) for j in range(8)]).reshape(8, 8))

In [8]:
# atol = 1e-5
false_case_count = 0
count = 0
for begin_hour in range(0, 24):
    for k in range(1, 24):
        for l in range(1, 24):
            if begin_hour + k + l >= 24:
                continue
            count += 1
            
			# print(get_hour_k_step_transition_matrix(begin_hour, k))
            tmp_bool = np.allclose(
                get_hour_k_step_transition_matrix(begin_hour, k+l),
                np.dot(get_hour_k_step_transition_matrix(begin_hour, k), 
                       get_hour_k_step_transition_matrix(begin_hour + k, l)), 
                       )
            if not tmp_bool:
                print((begin_hour, k, l), ' this is the pair of (begin_hour, k, l)')
                false_case_count += 1

print(count, " this is the count")
print(false_case_count, " this is the false case count")

(0, 1, 2)  this is the pair of (begin_hour, k, l)
(0, 1, 3)  this is the pair of (begin_hour, k, l)
(0, 1, 4)  this is the pair of (begin_hour, k, l)
(0, 1, 5)  this is the pair of (begin_hour, k, l)
(0, 1, 6)  this is the pair of (begin_hour, k, l)
(0, 1, 7)  this is the pair of (begin_hour, k, l)
(0, 1, 8)  this is the pair of (begin_hour, k, l)
(0, 1, 9)  this is the pair of (begin_hour, k, l)
(0, 1, 10)  this is the pair of (begin_hour, k, l)
(0, 1, 11)  this is the pair of (begin_hour, k, l)
(0, 1, 12)  this is the pair of (begin_hour, k, l)
(0, 1, 13)  this is the pair of (begin_hour, k, l)
(0, 1, 14)  this is the pair of (begin_hour, k, l)
(0, 1, 15)  this is the pair of (begin_hour, k, l)
(0, 1, 16)  this is the pair of (begin_hour, k, l)
(0, 1, 17)  this is the pair of (begin_hour, k, l)
(0, 1, 18)  this is the pair of (begin_hour, k, l)
(0, 1, 19)  this is the pair of (begin_hour, k, l)
(0, 1, 20)  this is the pair of (begin_hour, k, l)
(0, 1, 21)  this is the pair of (begin_

In [9]:
# # TODO(BobHuangC) Check the correctness of the k-step transition probability matrix calculation
# # 实验0 马尔科夫链的构造与 k 步转移概率矩阵的计算
# exp0_hour1 = 0
# exp0_hour2 = 1
# exp0_hour3 = 2

# print("Experiment 0")
# print('The construction of Markov Chain and the calculation of k-step transition probability matrix')
# print('--------------------------------------------------')
# # print(Region_1.getTransitionMatrix2Regions(begin_hour=exp0_hour1, end_hour=exp0_hour3))

# def get_k_step_transition_matrix(begin_hour, end_hour):
# 	transition_matrix = np.zeros((8, 8))
# 	transition_matrix[0] = Region_1.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	transition_matrix[1] = Region_2.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	transition_matrix[2] = Region_3.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	transition_matrix[3] = Region_4.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	transition_matrix[4] = Region_5.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	transition_matrix[5] = Region_6.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	transition_matrix[6] = Region_7.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	transition_matrix[7] = Region_8.getTransitionMatrix2Regions(begin_hour, end_hour)
# 	return transition_matrix


# hour0_step1_transition_matrix = get_k_step_transition_matrix(begin_hour = exp0_hour1, end_hour=exp0_hour2)
# hour1_step1_transition_matrix = get_k_step_transition_matrix(begin_hour = exp0_hour2, end_hour=exp0_hour3)
# hour0_step2_transition_matrix = get_k_step_transition_matrix(begin_hour=exp0_hour1, end_hour=exp0_hour3)

# print(hour0_step1_transition_matrix)
# # print(hour0_step1_transition_matrix.dot(hour1_step1_transition_matrix))

In [10]:
# # 实验1: 查普曼-柯尔莫哥洛夫方程验证
# # use the discrete time Markov chain model to analize the traffic flow
# _tmp = (hour0_step2_transition_matrix - np.dot(hour0_step1_transition_matrix, hour1_step1_transition_matrix))
# for i in range(8):
# 	for j in range(8):
# 		if abs(_tmp[i][j]) > 1e-4:
# 			print(i)
# 			print(j)
# 			print(_tmp[i][j])
# 			print("The Chapman-Kolmogorov equation is not satisfied.")
# 			# break
# # print(np.allclose(hour0_step2_transition_matrix, hour0_step1_transition_matrix.dot(hour1_step1_transition_matrix), atol=1e-3))

In [11]:
# # TODO(BobHuangC) to find a suitable hour then to calculate the transition matrix
# # 实验2: 时齐离散马尔科夫链的构造与极限分布与平稳分布的计算

# # Suppose the traffic flow is a time-homogeneous Markov chain
# # The transition matrix is the same for all hours

# for begin_hour in range(24):
#     _transition_matrix_P = get_k_step_transition_matrix(begin_hour, begin_hour+1)
#     # print(_transition_matrix_P)

# chosen_hour = 12
# transition_matrix_P = get_k_step_transition_matrix(chosen_hour, chosen_hour+1)
# # print(transition_matrix_P)


# # 根据transition matrix和初始分别计算极限分布
# def compute_limit_distribution(transition_matrix, initial_distribution, alltol = 1e-6):
# 	next_distribution = np.dot(initial_distribution, transition_matrix)
# 	while not np.allclose(initial_distribution, next_distribution, atol=alltol):
# 		initial_distribution = next_distribution
# 		next_distribution = np.dot(initial_distribution, transition_matrix)
# 	# 计算极限分布
# 	# limit_distribution = np.dot(initial_distribution, np.linalg.matrix_power(transition_matrix, 1000))
# 	return next_distribution



# initial_distribution = np.array([region_1_initial_traffic_amount, region_2_initial_traffic_amount,
# 								  region_3_initial_traffic_amount, region_4_initial_traffic_amount,
# 								  region_5_initial_traffic_amount, region_6_initial_traffic_amount,
# 								  region_7_initial_traffic_amount, region_8_initial_traffic_amount])
# initial_distribution = initial_distribution / np.sum(initial_distribution)
# limit_distribution = compute_limit_distribution(transition_matrix_P, initial_distribution)
# print('The limit distribution of the traffic flow:')
# print(limit_distribution)



# # 根据transition matrix计算平稳分布
# def compute_stationary_distribution(transition_matrix):
# 	eigenvalues, eigenvectors = np.linalg.eig(transition_matrix.T)
# 	stationary_index = np.where(np.isclose(eigenvalues, 1))[0][0]
# 	stationary_distribution = np.real(eigenvectors[:, stationary_index])
# 	stationary_distribution /= np.sum(stationary_distribution)
# 	return stationary_distribution

# transition_matrix_P = np.array(transition_matrix_P)

# stationary_distribution = compute_stationary_distribution(transition_matrix_P)
# print(stationary_distribution)

# # transition_matrix_P = get_k_step_transition_matrix(begin_hour=12, end_hour=13)
# # print(transition_matrix_P)

In [12]:
# # 实验3: 非时齐离散马尔科夫链的构造, 尝试用一些简单的方法构造非时齐马尔科夫链

# # 上面的实验明显表示用时齐马尔科夫链来模拟交通流是不合适的, 因为交通流是非时齐的
# # 结合我们日常生活中的经验, 明显交通流是非时齐的, 甚至transition matrix会是相反的, 例如在早上, 人们主要从住宅区到工作区, 而在晚上, 人们主要从工作区到住宅区
# # 而且交通流有明显的昼夜因素的影响, 
# # 以及交通流会明显地受到天气和节假日的影响
# # 因此我们尝试缩短时间范围, 在小范围内预测交通, 甚至我们在小范围内, 对非时齐的马尔科夫链进行建模


# # 6 - 9这个时间段.
# # 我们使用线性建模转移概率矩阵的方式来构造非时齐的马尔科夫链

# begin_hour = 6
# end_hour = 9
# # 我们结合6-7 的转移矩阵和 7-8 的转移矩阵来构造 8-9 的转移矩阵
# transition_matrix_6_7 = get_k_step_transition_matrix(begin_hour = 6, end_hour = 7)
# transition_matrix_7_8 = get_k_step_transition_matrix(begin_hour = 7, end_hour = 8)
# model_transition_matrix_8_9 = 2 * transition_matrix_7_8 - transition_matrix_6_7
# real_transition_matrix_8_9 = get_k_step_transition_matrix(begin_hour = 8, end_hour = 9)

# # print(transition_matrix_6_7)
# # print(transition_matrix_7_8)
# # print(model_transition_matrix_8_9)
# # print(real_transition_matrix_8_9)

# # TODO(BobHuangC) 预测具体的交通流量
# print('The real transition number is ')
# print(Region_1.getTransition2Region(begin_hour=8, end_hour=9))

# print('The Non Time Alignment model transition number is ')
# print(Region_1.getTrafficAmountByHour(hour=8) * model_transition_matrix_8_9[0])

# print('The Time Alignment model transition number is ')
# print(Region_1.getTrafficAmountByHour(hour=8) * (transition_matrix_6_7+transition_matrix_7_8)[0]/2)

In [13]:
# # 实验4: 时齐连续马尔科夫链的构造与Q矩阵的计算与极限分布与平稳分布的计算, 

# # 转移速率矩阵Q的计算

# transition_matrix_P1 = get_k_step_transition_matrix(begin_hour=12, end_hour=13)
# transition_matrix_P2 = get_k_step_transition_matrix(begin_hour=12, end_hour=14)
# transition_matrix_P3 = get_k_step_transition_matrix(begin_hour=12, end_hour=15)
# transition_matrix_P4 = get_k_step_transition_matrix(begin_hour=12, end_hour=16)

# Q1 = transition_matrix_P1 - np.eye(8)
# Q2 = (transition_matrix_P2 - np.eye(8)) / 2
# Q3 = (transition_matrix_P3 - np.eye(8)) / 3
# Q4 = (transition_matrix_P4 - np.eye(8)) / 4

# print(Q1)
# print(Q2)
# print(Q3)
# print(Q4)

# Q = Q1

In [14]:
# # 实验5: 时齐连续马尔科夫链根据Q矩阵计算平稳分布

# # 根据Q计算平稳分布
# def compute_stationary_distribution_by_Q(Q):
# 	Q = Q.T
# 	Q[-1] = np.ones(8)
# 	b = np.zeros(8)
# 	b[-1] = 1
# 	return np.linalg.solve(Q, b)

# stationary_distribution = compute_stationary_distribution_by_Q(Q)
# print(stationary_distribution)

In [15]:
# # 实验6: 非时齐连续马尔科夫链的构造, 尝试用一些简单的方法构造非时齐马尔科夫链

# # 对Q采取线性插值的方式来构造非时齐的Q矩阵


# transition_matrix_P_6_7 = get_k_step_transition_matrix(begin_hour=6, end_hour=7)
# transition_matrix_P_6_8 = get_k_step_transition_matrix(begin_hour=6, end_hour=8)
# transition_matrix_P_6_9 = get_k_step_transition_matrix(begin_hour=6, end_hour=9)
# transition_matrix_P_7_8 = get_k_step_transition_matrix(begin_hour=7, end_hour=8)
# transition_matrix_P_7_9 = get_k_step_transition_matrix(begin_hour=7, end_hour=9)
# transition_matrix_P_7_10 = get_k_step_transition_matrix(begin_hour=7, end_hour=10)

# Q1 = transition_matrix_P1 - np.eye(8)
# Q2 = (transition_matrix_P2 - np.eye(8)) / 2
# Q3 = (transition_matrix_P3 - np.eye(8)) / 3
# Q4 = (transition_matrix_P4 - np.eye(8)) / 4

# Q_hour6 = transition_matrix_P_6_7 - np.eye(8)
# Q_hour7 = transition_matrix_P_7_8 - np.eye(8)
# model_Q_hour8 = 2 * Q_hour7 - Q_hour6
# real_Q_hour8 = get_k_step_transition_matrix(begin_hour=8, end_hour=9) - np.eye(8)

# print(model_Q_hour8)
# print(real_Q_hour8)